-- Create the vehicles table in Supabase
create table if not exists vehicles (
  id bigint generated by default as identity primary key,
  title text,
  vin text,
  price numeric,
  mileage numeric,
  year numeric,
  fuel_type text,
  transmission text,
  listing_url text unique, -- Use URL as unique identifier to avoid duplicates if desired
  website_url text,
  exterior_color text,
  engine text,
  trim text,
  scraped_at timestamptz default now()
);

-- Optional: Create an index on listing_url for faster lookups
create index if not exists vehicles_listing_url_idx on vehicles (listing_url);
